@extends('layouts.app')
@section('title','Create customer account')
@section('content')
<main class="register-page"><section class="register-shell"><aside><img src="{{ asset('kermits-logo.jpg') }}" alt="Kermit's"><div><span>CUSTOMER ACCOUNT</span><h1>Order your<br>favorites.</h1><p>Create an account to place orders securely and keep each purchase connected to you.</p></div></aside><div class="register-form"><div><p class="eyebrow">SIGN UP</p><h2>Create your account</h2><p class="muted">Already registered? <a href="{{ route('login') }}">Log in</a>.</p>@if($errors->any())<div class="error register-error">{{ $errors->first() }}</div>@endif<form method="POST" action="{{ route('register.store') }}">@csrf<div class="field"><label>Full name</label><input class="control" name="name" value="{{ old('name') }}" maxlength="120" required></div><div class="field"><label>Username</label><input class="control" name="username" value="{{ old('username') }}" minlength="3" maxlength="50" pattern="[A-Za-z0-9._-]+" autocomplete="username" required><small>Letters, numbers, dots, underscores, and hyphens only.</small></div><div class="field"><label>Email address</label><input class="control" name="email" type="email" value="{{ old('email') }}" autocomplete="email" required></div><div class="field"><label>Phone number</label><input class="control" name="phone" type="tel" inputmode="numeric" value="{{ old('phone') }}" minlength="11" maxlength="11" pattern="09[0-9]{9}" placeholder="09XXXXXXXXX" required><small>11 digits starting with 09.</small></div><div class="field"><label>Password</label><input class="control" name="password" type="password" minlength="8" autocomplete="new-password" required></div><div class="field"><label>Confirm password</label><input class="control" name="password_confirmation" type="password" minlength="8" autocomplete="new-password" required></div><button class="register-button">Create account <span>&rarr;</span></button></form></div></div></section></main>
<style>.register-page{min-height:100dvh;display:grid;place-items:center;padding:12px;background:#dfe2de}.register-shell{width:min(1050px,100%);height:min(760px,calc(100dvh - 24px));min-height:620px;display:grid;grid-template-columns:1fr 1.05fr;border:8px solid #181918;border-radius:28px;overflow:hidden;background:#f5f6ef}.register-shell aside{background:#171817;color:#fff;padding:42px;display:flex;flex-direction:column}.register-shell aside img{width:86px;height:86px;border-radius:50%;object-fit:contain;background:#fff;padding:7px}.register-shell aside div{margin:auto 0}.register-shell aside span,.eyebrow{font-size:12px;letter-spacing:.16em;color:#aab514}.register-shell aside h1{font-size:40px;line-height:1.08;margin:12px 0}.register-shell aside p{color:#b9bcb5;line-height:1.7}.register-form{display:grid;place-items:center;padding:26px;overflow:auto}.register-form>div{width:min(410px,100%)}.register-form h2{font-size:29px;margin:7px 0}.register-error{background:#fff0f0;padding:12px;border-radius:9px;margin-bottom:14px}.register-button{width:100%;border:0;border-radius:11px;padding:14px 17px;background:#171817;color:#fff;font-weight:700;display:flex;justify-content:space-between}@media(max-width:760px){.register-page{padding:0}.register-shell{height:auto;min-height:100dvh;border:0;border-radius:0;grid-template-columns:1fr}.register-shell aside{padding:18px;min-height:140px}.register-shell aside img{width:54px;height:54px}.register-shell aside div{margin:10px 0}.register-shell aside h1{font-size:23px;margin:4px 0}.register-shell aside p{display:none}.register-form{padding:24px 20px}}</style>
<style>
body{background:#f5f5ef}.register-page{display:block;min-height:100dvh;padding:0}.register-shell{width:100%;height:100dvh;min-height:680px;grid-template-columns:minmax(350px,44%) minmax(0,56%);border:0;border-radius:0;background:#f7f7f1}.register-shell aside{padding:clamp(36px,5vw,72px);background:radial-gradient(circle at 15% 15%,#30332b 0,transparent 28%),linear-gradient(145deg,#131413,#1c1e1a)}.register-shell aside img{width:clamp(88px,8vw,120px);height:clamp(88px,8vw,120px)}.register-shell aside h1{font-size:clamp(42px,4vw,62px);letter-spacing:-.04em}.register-form{padding:clamp(28px,5vw,72px);background:radial-gradient(circle at 100% 0,#f0f1d8 0,transparent 32%),#f7f7f1}.register-form>div{width:min(520px,100%)}.register-form>div>.global-back{width:max-content;margin-bottom:34px;background:#fffefa;box-shadow:0 8px 24px rgba(22,24,20,.08)}.register-form h2{font-size:clamp(31px,3vw,42px)}.register-form .control{min-height:50px;border-radius:12px}.register-button{min-height:54px;border-radius:13px;font-size:16px;box-shadow:0 10px 24px rgba(23,24,23,.16)}
@media(max-width:800px){.register-shell{height:auto;min-height:100dvh;grid-template-columns:1fr}.register-shell aside{min-height:170px;padding:22px}.register-shell aside img{width:62px;height:62px}.register-shell aside div{margin:14px 0 0}.register-shell aside h1{font-size:27px}.register-shell aside p{display:none}.register-form{overflow:visible;padding:24px 18px 44px}.register-form>div>.global-back{margin-bottom:24px}}
</style>
@endsection
