@extends('layouts.app')
@section('title','Kermit’s Dashboard')
@section('content')
<div class="admin-shell">
@include('partials.admin-sidebar')
<main class="admin-workspace">
    <header class="dash-head"><div><p>STORE OVERVIEW</p><h1>Hi, here’s what’s happening<br>at Kermit’s</h1></div><time class="date-chip" id="dashboard-date" datetime="{{ now()->toDateString() }}">{{ now()->format('F d, Y') }}</time></header>
    <section class="hero-metrics">
        <div><span>Total sales</span><strong>₱{{ number_format($sales,2) }}</strong><small>Across {{ $ordersCount }} completed orders</small></div>
        <div class="sales-visual"><div class="bars">@foreach($salesActivity as $day)<i tabindex="0" style="height:{{ $day['height'] }}%" data-tooltip="{{ $day['label'] }} · ₱{{ number_format($day['amount'],2) }}" aria-label="{{ $day['label'] }} sales: ₱{{ number_format($day['amount'],2) }}"></i>@endforeach</div><small>Sales activity · hover a bar for details</small></div>
        <div class="mini-metric"><span>Average sale</span><strong>₱{{ number_format($averageSale,2) }}</strong><span>Items sold</span><strong>{{ number_format($itemsSold) }}</strong></div>
    </section>
    <section class="stat-row"><div><span>Active products</span><strong>{{ $productsCount }}</strong><small>Available in catalog</small></div><div><span>Low stock alerts</span><strong>{{ $lowStock->count() }}</strong><small>Products need attention</small></div><div><span>Transactions</span><strong>{{ $ordersCount }}</strong><small>All recorded sales</small></div></section>
    <div class="dash-grid">
        <section class="panel"><div class="panel-head"><div><h2>Recent sales</h2><p>Latest completed transactions</p></div>@if(auth()->user()->hasRole('super_admin'))<a href="{{ route('reports') }}">View reports</a>@endif</div>
        <div class="sales-list">@forelse($recentOrders as $order)<a href="{{ route('receipts.show',$order) }}"><span class="order-mark">#{{ $order->id }}</span><div><strong>{{ $order->user->name }}</strong><small>{{ $order->created_at->format('M d · h:i A') }} · {{ ucfirst($order->payment_method) }}</small></div><b>₱{{ number_format($order->total,2) }}</b></a>@empty<p class="empty">No sales yet. Open the cashier to record your first transaction.</p>@endforelse</div></section>
        <section class="panel"><div class="panel-head"><div><h2>Inventory alerts</h2><p>Items running low</p></div>@if(auth()->user()->hasRole('super_admin'))<a href="{{ route('products.index') }}">Manage</a>@endif</div>
        <div class="stock-list">@forelse($lowStock as $product)<div>@if($imageUrl = $product->imageUrl())<img src="{{ $imageUrl }}" alt="">@else<span>{{ strtoupper(substr($product->name,0,1)) }}</span>@endif<div><strong>{{ $product->name }}</strong><small>Only {{ $product->stock }} remaining</small></div><b>{{ $product->stock }}</b></div>@empty<p class="empty">Stock levels look healthy.</p>@endforelse</div></section>
    </div>
</main>
</div>
<style>
body{background:#dfe2de}.app-shell{width:min(1440px,calc(100% - 48px));min-height:calc(100vh - 48px);margin:24px auto;display:grid;grid-template-columns:260px 1fr;background:#f5f6ef;border:10px solid #181918;border-radius:30px;overflow:hidden;box-shadow:0 30px 80px rgba(22,25,22,.15)}
.sidebar{background:#171817;color:#f7f7f2;padding:28px 20px;display:flex;flex-direction:column}.side-brand{display:flex;align-items:center;gap:12px;margin-bottom:42px;padding:0 8px}.side-brand img{width:46px;height:46px;border-radius:50%;object-fit:contain;background:white;padding:4px}.side-brand strong{letter-spacing:.12em}.side-nav{display:grid;gap:8px}.side-nav a{color:#d8d9d5;text-decoration:none;padding:13px 15px;border-radius:10px;display:flex;align-items:center;gap:14px}.side-nav a span{font-size:20px;width:22px;text-align:center}.side-nav a:hover,.side-nav a.active{color:white;background:#292b27}.side-nav a.active{box-shadow:inset 3px 0 #b7c31b}.side-user{margin-top:auto;display:flex;align-items:center;gap:10px;padding:14px 6px}.side-user>span{width:36px;height:36px;border-radius:50%;display:grid;place-items:center;background:#aab514;color:#111}.side-user div{display:grid;flex:1}.side-user small{color:#969991;margin-top:2px}.side-user form{margin:0}.side-user button{border:0;background:none;color:white;font-size:18px;cursor:pointer}
.workspace{padding:34px;min-width:0}.dash-head{display:flex;justify-content:space-between;align-items:start;margin-bottom:26px}.dash-head p{font-size:12px;letter-spacing:.15em;color:#74786f;margin:0 0 8px}.dash-head h1{font-size:36px;line-height:1.08;margin:0}.date-chip{background:white;border:1px solid #d8dbd0;border-radius:10px;padding:12px 16px}.hero-metrics,.panel,.stat-row>div{background:#fff;border:1px solid #daddd1;border-radius:18px}.hero-metrics{padding:26px;display:grid;grid-template-columns:1fr 1.4fr .8fr;gap:28px;align-items:center}.hero-metrics span,.stat-row span{display:block;color:#656960;font-size:14px}.hero-metrics>div>strong{display:block;font-size:34px;margin:7px 0}.hero-metrics small,.stat-row small,.panel-head p,.sales-list small,.stock-list small{color:#777b72}.bars{height:115px;display:flex;align-items:end;gap:8px;border-bottom:1px solid #dfe2d8;overflow:visible}.bars i{position:relative;flex:1;min-width:5px;background:linear-gradient(#aab514,#e8ecc3);border-radius:4px 4px 0 0;cursor:help;outline:none}.bars i:hover,.bars i:focus{background:linear-gradient(#778300,#cdd68c)}.bars i:after{content:attr(data-tooltip);position:absolute;z-index:10;left:50%;bottom:calc(100% + 9px);transform:translateX(-50%);width:max-content;max-width:170px;padding:7px 9px;border-radius:8px;background:#171817;color:#fff;font:700 11px/1.3 system-ui;box-shadow:0 8px 22px rgba(0,0,0,.22);opacity:0;visibility:hidden;pointer-events:none}.bars i:hover:after,.bars i:focus:after{opacity:1;visibility:visible}.mini-metric{border-left:1px solid #e1e3da;padding-left:25px}.mini-metric strong{font-size:24px!important;margin:5px 0 18px!important}.stat-row{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:18px 0}.stat-row>div{padding:20px}.stat-row strong{display:block;font-size:27px;margin:6px 0}.dash-grid{display:grid;grid-template-columns:1.5fr 1fr;gap:18px}.panel{padding:24px}.panel-head{display:flex;justify-content:space-between;align-items:start;margin-bottom:15px}.panel-head h2{margin:0 0 4px;font-size:19px}.panel-head p{margin:0;font-size:13px}.panel-head a{color:#161714;font-size:13px}.sales-list,.stock-list{display:grid}.sales-list a,.stock-list>div{display:flex;align-items:center;gap:12px;padding:13px 0;border-top:1px solid #eceee7;color:inherit;text-decoration:none}.sales-list a>div,.stock-list>div>div{display:grid;flex:1}.order-mark,.stock-list img,.stock-list>div>span{width:42px;height:42px;border-radius:10px;background:#f0f2e1;display:grid;place-items:center;color:#747d00;font-size:12px}.stock-list img{object-fit:cover}.empty{color:#777b72;padding:24px 0}.panel b{white-space:nowrap}
@media(max-width:900px){.app-shell{width:100%;margin:0;border:0;border-radius:0;grid-template-columns:1fr}.sidebar{padding:14px;position:relative}.side-brand{margin:0}.side-nav{display:flex;overflow:auto;margin-top:12px}.side-user{display:none}.workspace{padding:22px}.hero-metrics{grid-template-columns:1fr}.mini-metric{border-left:0;padding-left:0}.dash-grid{grid-template-columns:1fr}.dash-head h1{font-size:28px}}@media(max-width:600px){.date-chip{display:none}.stat-row{grid-template-columns:1fr}.workspace{padding:16px}.app-shell{min-height:100vh}.hero-metrics{padding:20px}}
@media(min-width:901px){.app-shell{width:min(1440px,calc(100% - 24px));height:calc(100dvh - 24px);min-height:540px;margin:12px auto;grid-template-columns:clamp(210px,18vw,260px) minmax(0,1fr);border-width:8px;border-radius:26px}.sidebar{min-height:0;overflow:hidden;padding:clamp(16px,3vh,28px) 16px}.side-brand{margin-bottom:clamp(16px,4vh,42px)}.side-nav{min-height:0;overflow-y:auto}.side-nav a{padding:clamp(8px,1.4vh,13px) 13px}.side-user{flex-shrink:0}.workspace{height:100%;overflow-y:auto;overflow-x:hidden;padding:clamp(20px,3vw,34px)}}
@media(max-height:650px) and (min-width:901px){.side-brand{margin-bottom:10px}.side-brand img{width:38px;height:38px}.side-nav{gap:3px}.side-nav a{padding:7px 11px}.workspace{padding:18px}}
</style>

<script>(()=>{const date=document.getElementById('dashboard-date');if(!date)return;const refresh=()=>{const now=new Date(),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now),value=Object.fromEntries(parts.map(part=>[part.type,part.value]));date.dateTime=`${value.year}-${value.month}-${value.day}`;date.textContent=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Manila',year:'numeric',month:'long',day:'2-digit'}).format(now)};refresh();setInterval(refresh,60000)})();</script>
@endsection
