@extends('layouts.app')
@section('title', "Order from Kermit's")
@section('content')
<main class="customer-shop">
    <nav>
        <a href="{{ route('home') }}"><img src="{{ asset('kermits-logo.jpg') }}" alt="Kermit's"><strong>KERMIT'S</strong></a>
        <div class="customer-actions"><a class="active" href="{{ route('shop') }}" aria-current="page">Shop</a><a href="{{ route('customer.history') }}">History</a><a href="{{ route('reservations.create') }}">Reserve</a><span>Hi, {{ auth()->user()->name }}</span><form method="POST" action="{{ route('logout') }}">@csrf<button class="logout-icon" type="submit" title="Log out" aria-label="Log out"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10 5H6a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h4M14 8l4 4-4 4M18 12H9"/></svg></button></form></div>
    </nav>
    <header><p>ONLINE ORDER</p><h1>Choose your favorites</h1><span>Browse Kermit's complete menu by category.</span></header>
    @if($errors->any())<div class="error shop-error">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ route('shop.orders.store') }}">@csrf
        <div class="shop-grid">
            @forelse($products->groupBy('category') as $category => $items)
                <h2 class="menu-category">{{ $category }}</h2>
                @foreach($items as $product)
                    <article>
                        @if($product->image_path)<img src="{{ asset('storage/'.$product->image_path) }}" alt="{{ $product->name }}">@else<div class="shop-placeholder">{{ strtoupper(substr($product->name,0,1)) }}</div>@endif
                        <div><h3>{{ $product->name }}</h3><p>{{ $product->description }}</p><div class="shop-price"><strong>&#8369;{{ number_format($product->price,2) }}</strong><span>{{ $product->stock }} available</span></div><label>Quantity</label><input name="quantities[{{ $product->id }}]" type="number" min="0" max="{{ $product->stock }}" value="{{ old('quantities.'.$product->id,0) }}"></div>
                    </article>
                @endforeach
            @empty
                <p>No menu items are available.</p>
            @endforelse
        </div>
        <div class="order-bar"><div><strong>Ready to order?</strong><small>Review your items and choose Cash or GCash.</small></div><button type="button" data-checkout-open>Review & payment <span>&rarr;</span></button></div>
        <div class="checkout-modal" data-checkout-modal hidden>
            <button class="checkout-backdrop" type="button" aria-label="Close payment" data-checkout-close></button>
            <section class="checkout-panel" role="dialog" aria-modal="true" aria-labelledby="checkout-title">
                <header><div><p>ORDER CHECKOUT</p><h2 id="checkout-title">Choose payment method</h2><span>Your selected products will be reserved after submission.</span></div><button type="button" aria-label="Close payment" data-checkout-close>&times;</button></header>
                <div class="checkout-options">
                    <label><input type="radio" name="payment_method" value="cash" @checked(old('payment_method','cash')==='cash')><span><strong>Cash</strong><small>Pay the exact total at the counter when collecting your order.</small></span></label>
                    <label><input type="radio" name="payment_method" value="gcash" @checked(old('payment_method')==='gcash')><span><strong>GCash</strong><small>Scan the QR and enter the 13-digit transaction reference.</small></span></label>
                </div>
                <div class="gcash-checkout" data-gcash-fields>
                    <div class="shop-qr"><img src="{{ $gcashQrPath ? asset('storage/'.$gcashQrPath) : asset('gcash-qr-placeholder.svg') }}" alt="Kermit's GCash QR code"><small>{{ $gcashQrPath ? 'Scan using your GCash app.' : 'The Super Admin has not uploaded the GCash QR yet.' }}</small></div>
                    <div class="field"><label for="payment_reference">GCash transaction reference</label><input class="control" id="payment_reference" name="payment_reference" value="{{ old('payment_reference') }}" inputmode="numeric" pattern="[0-9]{13}" minlength="13" maxlength="13" placeholder="Enter exactly 13 digits"><small>Use the reference shown after your successful GCash payment.</small></div>
                </div>
                <div class="checkout-note" data-payment-note></div>
                <button class="place-order-button" type="submit">Place my order <span>&rarr;</span></button>
            </section>
        </div>
    </form>
</main>
<style>
.customer-shop{min-height:100dvh;background:#f4f5ee;padding-bottom:110px}.customer-shop nav{height:78px;width:min(1180px,calc(100% - 30px));margin:auto;display:flex;align-items:center;justify-content:space-between}.customer-shop nav>a{display:flex;align-items:center;gap:10px;text-decoration:none}.customer-shop nav img{width:48px;height:48px;border-radius:50%;object-fit:contain;background:#fff}.customer-shop nav>a strong{letter-spacing:.1em}.customer-actions{display:flex;align-items:center;gap:8px}.customer-actions a{background:#171817;color:#fff;text-decoration:none;border-radius:9px;padding:9px 12px;font-size:13px;font-weight:700}.customer-actions a:first-child{background:#fff;color:#171817;border:1px solid #ccd0c5}.customer-actions form{margin:0}.customer-actions button{border:1px solid #ccd0c5;border-radius:9px;background:#fff;padding:9px 12px}.customer-shop header,.customer-shop>form,.shop-error{width:min(1180px,calc(100% - 30px));margin-inline:auto}.customer-shop header{padding:50px 0 30px}.customer-shop header p{font-size:12px;letter-spacing:.16em;color:#7a8300}.customer-shop header h1{font-family:Georgia,serif;font-size:48px;font-weight:500;margin:8px 0}.customer-shop header>span{color:#687286}.shop-error{background:#fff0f0;padding:12px;border-radius:9px}.shop-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.menu-category{grid-column:1/-1;font-family:Georgia,serif;font-size:28px;margin:28px 0 0;padding-bottom:10px;border-bottom:2px solid #171817}.shop-grid article{background:#fff;border:1px solid #daddd1;border-radius:17px;overflow:hidden}.shop-grid article>img,.shop-placeholder{width:100%;height:210px;object-fit:cover}.shop-placeholder{display:grid;place-items:center;background:#e9ecd4;color:#747d00;font-size:54px}.shop-grid article>div{padding:19px}.shop-grid h3{font-size:19px;margin:0 0 7px}.shop-grid p{color:#687286;height:39px;overflow:hidden;margin:0 0 15px}.shop-price{display:flex;justify-content:space-between;margin-bottom:14px}.shop-price span{font-size:12px;color:#687286}.shop-grid input{width:80px;border:1px solid #d7dce5;border-radius:9px;padding:9px}.order-bar{position:fixed;left:50%;bottom:14px;transform:translateX(-50%);width:min(760px,calc(100% - 28px));background:#171817;color:#fff;border-radius:16px;padding:16px 18px;display:flex;align-items:center;justify-content:space-between;box-shadow:0 20px 50px #0005}.order-bar div{display:grid}.order-bar small{color:#aaada6;margin-top:3px}.order-bar button{border:0;border-radius:10px;background:#b5c019;padding:12px 16px;font-weight:700}
@media(max-width:900px){.shop-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.customer-actions>span,.customer-shop nav>a strong{display:none}.customer-actions a{padding:8px;font-size:12px}}@media(max-width:580px){.customer-shop header{padding-top:30px}.customer-shop header h1{font-size:37px}.shop-grid{grid-template-columns:1fr}.order-bar div{display:none}.order-bar button{width:100%}}
</style>
<style>
.checkout-modal[hidden]{display:none}.checkout-modal{position:fixed;inset:0;z-index:100;display:grid;grid-template-columns:1fr minmax(340px,480px)}.checkout-backdrop{grid-column:1/-1;grid-row:1;border:0;background:rgba(12,13,12,.62);backdrop-filter:blur(4px)}.checkout-panel{grid-column:2;grid-row:1;z-index:1;height:100dvh;overflow-y:auto;background:#f8f7f1;padding:32px;box-shadow:-25px 0 60px #0004;scrollbar-width:none}.checkout-panel::-webkit-scrollbar{display:none}.checkout-panel>header{display:flex;justify-content:space-between;gap:18px;margin-bottom:26px}.checkout-panel>header p{margin:0 0 7px;color:#7b8500;font-size:11px;font-weight:850;letter-spacing:.14em}.checkout-panel>header h2{margin:0;font-size:28px}.checkout-panel>header span{display:block;color:#737970;margin-top:7px;line-height:1.5}.checkout-panel>header button{width:40px;height:40px;border:1px solid #d2d5cb;border-radius:10px;background:#fff;font-size:24px}.checkout-options{display:grid;grid-template-columns:1fr 1fr;gap:10px}.checkout-options>label{display:flex;align-items:flex-start;gap:10px;padding:15px;border:1px solid #d5d8ce;border-radius:13px;background:#fff;cursor:pointer}.checkout-options>label:has(input:checked){border-color:#9da708;background:#f6f8df;box-shadow:0 0 0 2px rgba(174,187,25,.13)}.checkout-options input{margin-top:4px}.checkout-options span{display:grid}.checkout-options small{color:#72776f;line-height:1.45;margin-top:4px}.gcash-checkout{display:grid;grid-template-columns:150px 1fr;gap:18px;align-items:center;margin-top:18px;padding:18px;border-radius:14px;background:#eef3e8}.gcash-checkout[hidden]{display:none}.shop-qr{text-align:center}.shop-qr img{width:140px;aspect-ratio:1;object-fit:contain;background:#fff;border:1px solid #d5d8ce;border-radius:12px;padding:8px}.shop-qr small{display:block;color:#676d64;font-size:10px;line-height:1.4;margin-top:6px}.gcash-checkout .field{margin:0}.gcash-checkout .field>label{display:block;font-weight:800;margin-bottom:7px}.gcash-checkout .control{width:100%;font-size:17px}.gcash-checkout .field small{display:block;color:#6f756c;line-height:1.4;margin-top:7px}.checkout-note{margin:18px 0;padding:13px 15px;border-radius:11px;background:#f0f1eb;color:#555c52;font-size:13px;line-height:1.5}.place-order-button{width:100%;min-height:52px;border:0;border-radius:12px;background:#171817;color:#fff;padding:14px 17px;display:flex;justify-content:space-between;font-weight:800;cursor:pointer}.place-order-button:hover{background:#30322e}@media(max-width:650px){.checkout-modal{grid-template-columns:1fr}.checkout-panel{grid-column:1;padding:22px 16px}.checkout-options{grid-template-columns:1fr}.gcash-checkout{grid-template-columns:1fr}.shop-qr img{width:min(220px,100%)}}
</style>
<script>
(() => {
    const modal=document.querySelector('[data-checkout-modal]'),open=document.querySelector('[data-checkout-open]'),closers=document.querySelectorAll('[data-checkout-close]'),methods=document.querySelectorAll('input[name="payment_method"]'),gcash=document.querySelector('[data-gcash-fields]'),reference=document.getElementById('payment_reference'),note=document.querySelector('[data-payment-note]');
    if(!modal)return;
    const sync=()=>{const method=document.querySelector('input[name="payment_method"]:checked')?.value||'cash',isGcash=method==='gcash';gcash.hidden=!isGcash;reference.required=isGcash;reference.disabled=!isGcash;note.textContent=isGcash?'Your order will remain pending while the GCash reference is checked.':'Bring payment to the counter when collecting your order.'};
    const show=()=>{modal.hidden=false;document.body.style.overflow='hidden';sync()};const hide=()=>{modal.hidden=true;document.body.style.overflow=''};
    open.addEventListener('click',show);closers.forEach(button=>button.addEventListener('click',hide));methods.forEach(method=>method.addEventListener('change',sync));reference.addEventListener('input',()=>reference.value=reference.value.replace(/\D/g,'').slice(0,13));sync();
    @if($errors->any()) show(); @endif
})();
</script>
<style>
/* Full-page customer shop */
@media(min-width:901px){
    .customer-shop{display:grid;grid-template-columns:250px minmax(0,1fr);grid-template-rows:auto 1fr;align-items:start;min-height:100dvh;padding:0 0 110px 0!important;background:#f5f4ed!important}
    .customer-shop>nav{position:fixed!important;inset:0 auto 0 0;width:250px!important;height:100dvh!important;padding:30px 20px!important;background:linear-gradient(160deg,#151615,#21231f)!important;border:0!important;display:flex!important;flex-direction:column;align-items:stretch!important;justify-content:flex-start!important;color:#fff;backdrop-filter:none!important}
    .customer-shop>nav>a{padding:4px 8px 28px;border-bottom:1px solid #343630}.customer-shop>nav img{width:58px;height:58px}.customer-shop>nav>a strong{color:#fff}
    .customer-shop .customer-actions{display:grid!important;grid-template-rows:auto auto auto 1fr auto auto;align-items:stretch!important;gap:8px!important;margin-top:28px;min-height:0;flex:1}.customer-shop .customer-actions>a{min-height:46px;display:flex;align-items:center;border:0!important;background:#292b27!important;color:#eee!important;padding:12px 14px!important}.customer-shop .customer-actions>a:hover{background:#363933!important}.customer-shop .customer-actions>a.active{background:#34372f!important;box-shadow:inset 4px 0 #b5c019}.customer-shop .customer-actions>span{grid-row:5;margin-top:0;padding:15px 12px 4px;color:#aeb2a9;font-size:13px;border-top:1px solid #343630}.customer-shop .customer-actions form{grid-row:6;margin-top:0}.customer-shop .customer-actions button{width:100%;min-height:44px;background:transparent!important;color:#fff;border-color:#464941!important}
    .customer-shop>header,.customer-shop>form,.customer-shop>.shop-error{grid-column:2;width:auto!important;margin-inline:0!important}.customer-shop>header{padding:38px clamp(26px,4vw,58px) 24px!important;background:#f5f4ed}.customer-shop>header h1{font-size:clamp(38px,4vw,56px)}.customer-shop>form{padding:0 clamp(26px,4vw,58px)}.customer-shop>.shop-error{margin:0 clamp(26px,4vw,58px) 18px!important}.customer-shop .shop-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.customer-shop .menu-category{margin-top:34px}.customer-shop .order-bar{left:calc(250px + (100vw - 250px)/2)!important;width:min(780px,calc(100vw - 290px))!important}
}
@media(min-width:901px) and (max-width:1220px){.customer-shop .shop-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:900px){.customer-shop{display:block;padding-bottom:100px!important}.customer-shop>nav{position:sticky!important}.customer-shop .shop-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.customer-shop>header{padding-top:32px!important}.customer-shop .order-bar{left:50%!important}}
@media(max-width:580px){.customer-shop .shop-grid{grid-template-columns:1fr}.customer-shop>nav{height:68px!important}.customer-shop>nav img{width:42px;height:42px}.customer-shop .customer-actions>span{display:none}.customer-shop>header{padding-top:24px!important}.customer-shop .menu-category{font-size:25px;margin-top:24px}.customer-shop .order-bar{width:calc(100% - 16px)!important}}
</style>
<style>@media(min-width:901px){.customer-shop .customer-actions{grid-template-columns:minmax(0,1fr) 42px!important;grid-template-rows:auto auto auto 1fr auto!important}.customer-shop .customer-actions>a{grid-column:1/-1}.customer-shop .customer-actions>span{grid-row:5!important;grid-column:1;margin:0!important;padding:15px 8px 0 12px!important;display:flex;align-items:center;min-height:58px}.customer-shop .customer-actions>form{grid-row:5!important;grid-column:2;margin:0!important;padding-top:15px;border-top:1px solid #343630;display:flex!important;align-items:center;justify-content:flex-end}.customer-shop .customer-actions .logout-icon{width:42px!important;height:42px!important;min-width:42px!important;min-height:42px!important}}</style>
@endsection
