const root = document.querySelector('#app');
const state = { token: localStorage.getItem('kermits_mobile_token'), user: null, products: [], cart: JSON.parse(localStorage.getItem('kermits_cart') || '{}'), tab: 'menu', category: 'All', query: '', busy: false, message: '' };
const money = value => `PHP ${Number(value).toLocaleString('en-PH', { minimumFractionDigits: 2 })}`;
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' })[char]);
const saveCart = () => localStorage.setItem('kermits_cart', JSON.stringify(state.cart));
const api = async (path, options = {}) => {
    const response = await fetch(`/api/v1${path}`, { ...options, headers: { Accept: 'application/json', 'Content-Type': 'application/json', ...(state.token ? { Authorization: `Bearer ${state.token}` } : {}), ...(options.headers || {}) } });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) { if (response.status === 401) { state.token = null; localStorage.removeItem('kermits_mobile_token'); render(); } throw new Error(body.message || Object.values(body.errors || {})[0]?.[0] || 'Something went wrong.'); }
    return body.data ?? body;
};
const formData = form => Object.fromEntries(new FormData(form).entries());
root.addEventListener('click', event => { if (!event.target.closest('[data-logout]')) return; api('/logout', { method: 'POST' }).catch(() => {}).finally(() => { state.token = null; localStorage.removeItem('kermits_mobile_token'); render(); }); });
function render() { root.innerHTML = state.token ? appTemplate() : loginTemplate(); if (state.token) root.querySelector('.brand').insertAdjacentHTML('beforeend', '<button data-logout style="margin-left:8px;border:1px solid #ffffff44;border-radius:8px;background:#ffffff12;color:#fff;padding:7px;font-size:11px">Sign out</button>'); bind(); }
function loginTemplate() { return `<main class="login"><div><div class="brand"><img src="/kermits-logo.jpg" alt="Kermit's logo"><strong>KERMIT'S RESTAURANT</strong></div><p class="eyebrow">CUSTOMER APP</p><h1>Good food, made easy.</h1><p class="muted">Order your favorites, reserve your table, and keep every detail close at hand.</p><form id="login-form" class="panel stack"><div class="field"><label for="login">Email or username</label><input id="login" name="login" autocomplete="username" required></div><div class="field"><label for="password">Password</label><input id="password" name="password" type="password" autocomplete="current-password" required></div><div id="form-message"></div><button class="primary" type="submit">Sign in</button><a class="link-button" href="/register">Create a customer account</a></form></div></main>`; }
function appTemplate() { const cartCount = Object.values(state.cart).reduce((sum, item) => sum + item.quantity, 0); return `<header class="app-header"><div class="brand"><img src="/kermits-logo.jpg" alt="Kermit's logo"><strong>KERMIT'S</strong><span style="margin-left:auto;font-size:12px">${escapeHtml(state.user?.name || '')}</span></div><p class="eyebrow">${state.tab === 'menu' ? 'WELCOME BACK' : state.tab.toUpperCase()}</p><h1>${state.tab === 'menu' ? 'What are you craving?' : state.tab === 'cart' ? 'Your order' : state.tab === 'orders' ? 'Order history' : 'Your reservations'}</h1></header><main class="content">${state.message ? `<div class="notice" id="flash">${escapeHtml(state.message)}</div>` : ''}${tabTemplate()}</main><nav class="bottom-nav"><button class="nav-button ${state.tab === 'menu' ? 'active' : ''}" data-tab="menu"><b>Menu</b>Browse</button><button class="nav-button ${state.tab === 'cart' ? 'active' : ''}" data-tab="cart"><b>${cartCount || '+'}</b>Cart</button><button class="nav-button ${state.tab === 'orders' ? 'active' : ''}" data-tab="orders"><b>History</b>Activity</button></nav>`; }
function tabTemplate() { if (state.tab === 'menu') return menuTemplate(); if (state.tab === 'cart') return cartTemplate(); return historyTemplate(); }
function menuTemplate() { const cats = ['All', ...new Set(state.products.map(product => product.category).filter(Boolean))]; const products = state.products.filter(product => (state.category === 'All' || product.category === state.category) && `${product.name} ${product.description || ''}`.toLowerCase().includes(state.query.toLowerCase())); return `<div class="search"><input id="product-search" value="${escapeHtml(state.query)}" placeholder="Search the menu" aria-label="Search menu"></div><div class="category-row">${cats.map(cat => `<button class="chip ${cat === state.category ? 'active' : ''}" data-category="${escapeHtml(cat)}">${escapeHtml(cat)}</button>`).join('')}</div><div class="product-list">${products.length ? products.map(product => `<article class="product"><img src="${escapeHtml(product.image_url || '/kermits-logo.jpg')}" alt=""><div><h3>${escapeHtml(product.name)}</h3><p>${escapeHtml(product.description || product.category || 'Prepared fresh.')}</p><div class="price">${money(product.price)}</div></div><button class="add" data-add="${product.id}" aria-label="Add ${escapeHtml(product.name)}">+</button></article>`).join('') : '<div class="empty">No menu items match that search.</div>'}</div>`; }
function cartTemplate() { const items = Object.values(state.cart); if (!items.length) return '<div class="panel empty">Your cart is empty.<br><button class="link-button" data-tab="menu">Browse the menu</button></div>'; const total = items.reduce((sum, item) => sum + item.price * item.quantity, 0); return `<section class="panel"><div class="section-title"><h2>Review order</h2><span class="badge">${items.length} items</span></div>${items.map(item => `<div class="cart-row"><div><strong>${escapeHtml(item.name)}</strong><div class="muted">${money(item.price)} each</div></div><div class="quantity"><button data-minus="${item.id}">-</button><strong>${item.quantity}</strong><button data-plus="${item.id}">+</button></div></div>`).join('')}<div class="total"><span>Total</span><span>${money(total)}</span></div></section><form id="order-form" class="panel stack" style="margin-top:13px"><div class="section-title"><h2>Payment</h2></div><div class="field"><label for="payment_method">Payment method</label><select id="payment_method" name="payment_method"><option value="cash">Cash on pickup</option><option value="gcash">GCash</option></select></div><div class="field"><label for="payment_reference">GCash reference <span class="muted">(required for GCash)</span></label><input id="payment_reference" name="payment_reference" inputmode="numeric" pattern="[0-9]{13}" maxlength="13"></div><div id="form-message"></div><button class="primary" type="submit">Place order</button></form>`; }
function historyTemplate() { return '<div class="stack"><button class="primary" data-new-reservation>Reserve a table</button><div class="empty">Loading activity...</div></div>'; }
async function loadHistory() { try { const [orders, reservations] = await Promise.all([api('/orders'), api('/reservations')]); root.querySelector('.content').innerHTML = `<div class="section-title"><h2>Reservations</h2><span class="badge">${reservations.length}</span></div><section class="panel" style="margin-bottom:18px">${reservations.length ? reservations.map(item => `<div class="history-row"><div><strong>${escapeHtml(item.reference)}</strong><div class="muted">${new Date(item.reservation_at).toLocaleString()}</div></div><span class="badge">${escapeHtml(item.status)}</span></div>`).join('') : '<div class="empty">No reservations yet.</div>'}</section><div class="section-title"><h2>Orders</h2><span class="badge">${orders.length}</span></div><section class="panel">${orders.length ? orders.map(item => `<div class="history-row"><div><strong>Order #${String(item.id).padStart(6, '0')}</strong><div class="muted">${new Date(item.created_at).toLocaleString()}</div></div><span class="badge">${escapeHtml(item.payment_status)}</span><strong>${money(item.total)}</strong></div>`).join('') : '<div class="empty">No orders yet.</div>'}</section>`; } catch (error) { showError(error.message); } }
async function loadApp() { try { state.user = await api('/me'); const catalog = await api('/products'); state.products = catalog.products || []; render(); } catch (error) { if (state.token) { state.message = error.message; render(); } } }
function showError(message) { const target = root.querySelector('#form-message'); if (target) target.innerHTML = `<div class="error">${escapeHtml(message)}</div>`; else { state.message = message; render(); } }
function bind() { root.querySelectorAll('[data-tab]').forEach(button => button.addEventListener('click', () => { state.tab = button.dataset.tab; state.message = ''; render(); if (state.tab === 'orders') loadHistory(); })); root.querySelectorAll('[data-category]').forEach(button => button.addEventListener('click', () => { state.category = button.dataset.category; render(); })); root.querySelector('#product-search')?.addEventListener('input', event => { state.query = event.target.value; render(); root.querySelector('#product-search')?.focus(); }); root.querySelectorAll('[data-add]').forEach(button => button.addEventListener('click', () => { const product = state.products.find(item => item.id === Number(button.dataset.add)); state.cart[product.id] = { ...product, quantity: (state.cart[product.id]?.quantity || 0) + 1 }; saveCart(); state.message = `${product.name} added to your cart.`; render(); })); root.querySelectorAll('[data-minus],[data-plus]').forEach(button => button.addEventListener('click', () => { const id = button.dataset.minus || button.dataset.plus; const amount = button.dataset.plus ? 1 : -1; state.cart[id].quantity += amount; if (state.cart[id].quantity < 1) delete state.cart[id]; saveCart(); render(); })); root.querySelector('#login-form')?.addEventListener('submit', login); root.querySelector('#order-form')?.addEventListener('submit', submitOrder); }
async function login(event) { event.preventDefault(); const button = event.target.querySelector('button'); button.disabled = true; try { const data = await api('/login', { method: 'POST', body: JSON.stringify({ ...formData(event.target), device_name: 'Kermits customer app' }) }); state.token = data.token; localStorage.setItem('kermits_mobile_token', state.token); state.user = data.user; await loadApp(); } catch (error) { showError(error.message); button.disabled = false; } }
async function submitOrder(event) { event.preventDefault(); const form = event.target; const values = formData(form); const payload = { items: Object.values(state.cart).map(item => ({ product_id: item.id, quantity: item.quantity })), payment_method: values.payment_method }; if (values.payment_reference) payload.payment_reference = values.payment_reference; const button = form.querySelector('button'); button.disabled = true; try { const order = await api('/orders', { method: 'POST', body: JSON.stringify(payload) }); state.cart = {}; saveCart(); state.tab = 'orders'; state.message = `Order #${String(order.id).padStart(6, '0')} submitted.`; render(); await loadHistory(); } catch (error) { showError(error.message); button.disabled = false; } }
function showReservationForm() { root.querySelector('.content').innerHTML = `<form id="reservation-form" class="panel stack"><div class="section-title"><h2>Reserve a table</h2></div><div class="field"><label>Table size</label><select name="table_size"><option value="1">1 seat</option><option value="2">2 seats</option><option value="4" selected>4 seats</option><option value="8">8 seats</option><option value="12">12 seats</option></select></div><div class="field"><label>Date and time</label><input name="reservation_at" type="datetime-local" required></div><div class="field"><label>Phone</label><input name="phone" inputmode="numeric" pattern="09[0-9]{9}" maxlength="11" placeholder="09XXXXXXXXX" required></div><div class="field"><label>Payment</label><select name="payment_method"><option value="cash">Cash</option><option value="gcash">GCash</option></select></div><div class="field"><label>GCash reference <span class="muted">(required for GCash)</span></label><input name="payment_reference" inputmode="numeric" pattern="[0-9]{13}" maxlength="13"></div><div class="field"><label>Notes</label><textarea name="notes" rows="3" maxlength="2000" placeholder="Anything we should know?"></textarea></div><div id="form-message"></div><button class="primary" type="submit">Send reservation request</button><button class="link-button" type="button" data-tab="orders">Cancel</button></form>`; bind(); root.querySelector('#reservation-form').addEventListener('submit', submitReservation); }
async function submitReservation(event) { event.preventDefault(); const form = event.target; const values = formData(form); const button = form.querySelector('button'); button.disabled = true; try { await api('/reservations', { method: 'POST', body: JSON.stringify({ type: 'table', table_size: Number(values.table_size), reservation_at: values.reservation_at, phone: values.phone, payment_method: values.payment_method, payment_reference: values.payment_reference || null, notes: values.notes || null }) }); state.message = 'Reservation request submitted.'; state.tab = 'orders'; render(); await loadHistory(); } catch (error) { showError(error.message); button.disabled = false; } }
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('/mobile-sw.js').catch(() => {}));
if (state.token) loadApp(); else render();
