@extends('layouts.app')
@section('title','Inventory')
@section('content')
<div class="admin-shell">@include('partials.admin-sidebar')<main class="admin-workspace"><div class="dashboard">
<header class="topbar"><div><h1 style="font-size:26px">Inventory</h1><p class="muted" style="margin:4px 0">Monitor and update product stock</p></div><a class="logout" style="text-decoration:none;color:inherit" href="{{ route('dashboard') }}">Dashboard</a></header>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="error" style="background:#fff0f0;padding:12px;border-radius:9px;margin-bottom:18px">{{ $errors->first() }}</div>@endif
<section style="display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:20px"><div class="welcome" style="padding:20px"><span class="muted">Products</span><h2>{{ $products->count() }}</h2></div><div class="welcome" style="padding:20px"><span class="muted">Total units</span><h2>{{ number_format($totalUnits) }}</h2></div><div class="welcome" style="padding:20px"><span class="muted">Low stock</span><h2 style="color:{{ $lowStock?'#c42b2b':'inherit' }}">{{ $lowStock }}</h2></div></section>
<section class="welcome" style="padding:24px;margin-bottom:20px"><h2 style="margin-top:0">Stock levels</h2><div class="inventory-grid">@foreach($products as $product)<article class="inventory-item">@if($product->image_path)<img src="{{ asset('storage/'.$product->image_path) }}" alt="">@else<div class="inventory-placeholder">{{ strtoupper(substr($product->name,0,1)) }}</div>@endif<div class="inventory-info"><h3>{{ $product->name }}</h3><span class="stock-badge {{ $product->stock<=5?'low':'' }}">{{ $product->stock }} units</span></div><form method="POST" action="{{ route('inventory.update',$product) }}">@csrf<div class="inventory-controls"><select class="control" name="type"><option value="stock_in">Stock in</option><option value="stock_out">Stock out</option><option value="adjustment">Set exact stock</option></select><input class="control" name="quantity" type="number" min="0" placeholder="Quantity" required><input class="control" name="note" placeholder="Note (optional)"><button class="button">Update</button></div></form></article>@endforeach</div></section>
<section class="welcome" style="padding:24px;overflow:auto"><h2 style="margin-top:0">Movement history</h2><table style="width:100%;border-collapse:collapse"><tr style="text-align:left"><th style="padding:10px">Date</th><th>Product</th><th>Type</th><th>Change</th><th>Before</th><th>After</th><th>By</th><th>Note</th></tr>@forelse($movements as $movement)<tr style="border-top:1px solid #e7eaf0"><td style="padding:12px">{{ $movement->created_at->format('M d, H:i') }}</td><td>{{ $movement->product->name }}</td><td>{{ str($movement->type)->replace('_',' ')->title() }}</td><td>{{ $movement->quantity>0?'+':'' }}{{ $movement->quantity }}</td><td>{{ $movement->stock_before }}</td><td>{{ $movement->stock_after }}</td><td>{{ $movement->user->name }}</td><td>{{ $movement->note ?: '—' }}</td></tr>@empty<tr><td colspan="8" style="padding:20px;color:#687286">No stock movements yet.</td></tr>@endforelse</table></section>
</div></main></div>
<style>.inventory-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.inventory-item{border:1px solid #e0e3d9;border-radius:14px;padding:16px;display:grid;grid-template-columns:58px 1fr;gap:12px}.inventory-item>img,.inventory-placeholder{width:58px;height:58px;border-radius:10px;object-fit:cover}.inventory-placeholder{display:grid;place-items:center;background:#eff1df;color:#747d00;font-weight:800}.inventory-info h3{margin:3px 0 8px}.stock-badge{font-size:12px;color:#267444}.stock-badge.low{color:#c42b2b}.inventory-item form{grid-column:1/-1}.inventory-controls{display:grid;grid-template-columns:1fr .7fr 1fr auto;gap:8px}.inventory-controls .button{width:auto}@media(max-width:1100px){.inventory-grid{grid-template-columns:1fr}.inventory-controls{grid-template-columns:1fr 1fr}}@media(max-width:520px){.inventory-controls{grid-template-columns:1fr}.inventory-controls .button{width:100%}}</style>
@endsection
