@extends('layouts.app')
@section('title','Cashier Accounts')
@section('content')
<div class="admin-shell">@include('partials.admin-sidebar')<main class="admin-workspace"><div class="dashboard cashier-accounts">
    <header class="topbar"><div><p>SUPER ADMIN</p><h1>Cashier accounts</h1><span>Create secure staff access for the point of sale.</span></div></header>
    @if(session('status'))<div class="notice account-notice">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="error account-notice">{{ $errors->first() }}</div>@endif
    <section class="cashier-summary-cards"><div class="welcome"><span>Active cashiers</span><h2>{{ $cashiers->count() }}</h2></div><div class="welcome"><span>Completed cashier sales</span><h2>{{ $cashiers->sum('paid_sales_count') }}</h2></div><div class="welcome"><span>Cashier sales value</span><h2>&#8369;{{ number_format($cashiers->sum('paid_sales_total'),2) }}</h2></div></section>
    <div class="cashier-account-grid">
        <section class="welcome create-cashier"><p>NEW CASHIER</p><h2>Create cashier account</h2><form method="POST" action="{{ route('cashiers.store') }}">@csrf
            <div class="field"><label for="name">Full name</label><input class="control" id="name" name="name" value="{{ old('name') }}" maxlength="120" required></div>
            <div class="field"><label for="username">Username</label><input class="control" id="username" name="username" value="{{ old('username') }}" minlength="3" maxlength="50" pattern="[A-Za-z0-9._-]+" autocomplete="username" required><small>Letters, numbers, dots, underscores, and hyphens only.</small></div>
            <div class="field"><label for="email">Email address</label><input class="control" id="email" name="email" type="email" value="{{ old('email') }}" autocomplete="email" required></div>
            <div class="field"><label for="phone">Phone number</label><input class="control" id="phone" name="phone" type="tel" inputmode="numeric" minlength="11" maxlength="11" pattern="09[0-9]{9}" value="{{ old('phone') }}" placeholder="09XXXXXXXXX" required><small>11 digits starting with 09.</small></div>
            <div class="field"><label for="password">Temporary password</label><input class="control" id="password" name="password" type="password" minlength="12" autocomplete="new-password" required><small>12+ characters with uppercase, lowercase, number, and symbol.</small></div>
            <div class="field"><label for="password_confirmation">Confirm password</label><input class="control" id="password_confirmation" name="password_confirmation" type="password" minlength="12" autocomplete="new-password" required></div>
            <button class="button" type="submit">Create cashier account</button>
        </form></section>
        <section class="welcome cashier-list"><div class="list-head"><div><p>CURRENT STAFF</p><h2>Cashier accounts</h2></div><strong>{{ $cashiers->count() }}</strong></div><div>@forelse($cashiers as $cashier)<article class="cashier-record"><div class="cashier-summary"><span>{{ strtoupper(substr($cashier->name,0,1)) }}</span><div><strong>{{ $cashier->name }}</strong><small>{{ $cashier->username ?: 'No username' }} · {{ $cashier->email }}</small><small>{{ $cashier->phone ?: 'No phone' }} · Created {{ $cashier->created_at->format('M d, Y') }}</small></div><b>Cashier</b></div><details><summary>Edit account</summary><form class="edit-cashier" method="POST" action="{{ route('cashiers.update',$cashier) }}">@csrf @method('PUT')<div class="field"><label>Full name</label><input class="control" name="name" value="{{ $cashier->name }}" required></div><div class="field"><label>Username</label><input class="control" name="username" value="{{ $cashier->username }}" minlength="3" maxlength="50" pattern="[A-Za-z0-9._-]+" required></div><div class="field"><label>Email</label><input class="control" name="email" type="email" value="{{ $cashier->email }}" required></div><div class="field"><label>Phone</label><input class="control" name="phone" type="tel" inputmode="numeric" minlength="11" maxlength="11" pattern="09[0-9]{9}" value="{{ $cashier->phone }}" required></div><div class="field"><label>New password <small>(optional)</small></label><input class="control" name="password" type="password" minlength="12" autocomplete="new-password"></div><div class="field"><label>Confirm password</label><input class="control" name="password_confirmation" type="password" minlength="12" autocomplete="new-password"></div><button class="button" type="submit">Save changes</button></form><form class="delete-cashier" method="POST" action="{{ route('cashiers.destroy',$cashier) }}" onsubmit="return confirm('Delete this cashier account? Login access will be removed, but sales records will remain.')">@csrf @method('DELETE')<button type="submit">Delete cashier account</button></form></details></article>@empty<div class="empty">No cashier accounts yet.</div>@endforelse</div></section>
    </div>
</div></main></div>
<style>.cashier-accounts .topbar{margin-bottom:20px}.cashier-accounts .topbar p,.create-cashier>p,.list-head p{margin:0;color:#7a8300;font-size:11px;letter-spacing:.16em}.cashier-accounts .topbar h1{margin:5px 0;font-size:30px}.cashier-accounts .topbar span{color:#687286}.account-notice{padding:12px;margin-bottom:14px;border-radius:10px}.cashier-summary-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:20px}.cashier-summary-cards>.welcome{padding:20px}.cashier-summary-cards span{color:#687286}.cashier-summary-cards h2{margin:6px 0 0;font-size:27px}.cashier-account-grid{display:grid;grid-template-columns:minmax(320px,.8fr) minmax(0,1.2fr);gap:20px}.create-cashier,.cashier-list{padding:24px;border-radius:15px!important}.create-cashier h2,.list-head h2{margin:5px 0 18px;font-size:20px}.create-cashier .field{margin-bottom:13px}.create-cashier small{display:block;color:#687286;margin-top:5px}.list-head{display:flex;justify-content:space-between;align-items:start}.list-head>strong{width:42px;height:42px;display:grid;place-items:center;border-radius:11px;background:#e9ecd4;color:#667000}.cashier-record{padding:14px 0;border-top:1px solid #e7eaf0}.cashier-summary{display:grid;grid-template-columns:44px minmax(0,1fr) auto;gap:12px;align-items:center}.cashier-summary>span{width:44px;height:44px;border-radius:50%;display:grid;place-items:center;background:#e9ecd4;color:#667000;font-weight:800}.cashier-summary>div{display:grid;min-width:0}.cashier-list small{color:#687286;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cashier-summary>b{font-size:11px;padding:5px 8px;border-radius:999px;background:#f0f1ed}.cashier-record details{margin:11px 0 0 56px}.cashier-record summary{width:max-content;color:#596100;font-weight:800;font-size:13px;cursor:pointer}.edit-cashier{display:grid;grid-template-columns:1fr 1fr;gap:9px 12px;margin-top:13px;padding:15px;background:#f5f6ef;border-radius:11px}.edit-cashier .field{margin:0}.edit-cashier .button{grid-column:1/-1}.delete-cashier{margin-top:10px;text-align:right}.delete-cashier button{border:1px solid #b42318;border-radius:9px;background:#fff7f7;color:#b42318;padding:9px 12px;font-weight:800;cursor:pointer}@media(max-width:950px){.cashier-account-grid{grid-template-columns:1fr}}@media(max-width:700px){.cashier-summary-cards{grid-template-columns:1fr}}@media(max-width:600px){.edit-cashier{grid-template-columns:1fr}.edit-cashier .button{grid-column:auto}.cashier-record details{margin-left:0}}@media(max-width:520px){.cashier-summary{grid-template-columns:40px minmax(0,1fr)}.cashier-summary>b{grid-column:2;width:max-content}}</style>
@endsection
