@extends('layouts.app')
@section('title','Receipt #'.$order->id)
@section('content')
<div class="admin-shell receipt-shell">@include('partials.admin-sidebar')<main class="admin-workspace"><div class="receipt-wrap">
    <header class="receipt-page-head"><div><p>TRANSACTION COMPLETE</p><h1>Receipt #{{ str_pad($order->id,6,'0',STR_PAD_LEFT) }}</h1></div><a class="logout" href="{{ route('cashier') }}">New sale</a></header>
    @if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
    <article class="receipt-card"><div class="receipt-brand"><img src="{{ asset('kermits-logo.jpg') }}" alt="Kermit's"><div><strong>KERMIT'S</strong><span>Official Receipt</span></div></div>
        <div class="receipt-meta"><div><span>Receipt</span><strong>#{{ str_pad($order->id,6,'0',STR_PAD_LEFT) }}</strong></div><div><span>Date</span><strong>{{ $order->created_at->format('M d, Y h:i A') }}</strong></div><div><span>Customer</span><strong>{{ $order->customer?->name ?? 'Walk-in Customer' }}</strong></div><div><span>Cashier</span><strong>{{ $order->user->name }}</strong></div><div><span>Payment</span><strong>{{ ucfirst($order->payment_method) }}</strong></div></div>
        <div class="receipt-items">@foreach($order->items as $item)<div><span><strong>{{ $item->product?->name ?? 'Product' }}</strong><small>{{ $item->quantity }} &times; &#8369;{{ number_format($item->unit_price,2) }}</small></span><b>&#8369;{{ number_format($item->subtotal,2) }}</b></div>@endforeach</div>
        <div class="receipt-total"><span>Total</span><strong>&#8369;{{ number_format($order->total,2) }}</strong></div>@if($order->cash_received !== null)<div style="display:grid;gap:8px;padding-top:14px"><span style="display:flex;justify-content:space-between">Cash received <b>&#8369;{{ number_format($order->cash_received,2) }}</b></span><span style="display:flex;justify-content:space-between">Change <b>&#8369;{{ number_format($order->change_due,2) }}</b></span></div>@elseif($order->payment_reference)<div style="display:flex;justify-content:space-between;gap:12px;padding-top:14px"><span>GCash reference</span><b>{{ $order->payment_reference }}</b></div>@endif<p class="receipt-thanks">Thank you for your purchase!</p>
    </article><div class="receipt-actions"><button class="button" onclick="window.print()">Print receipt</button><a class="logout" href="{{ route('cashier') }}">Return to POS</a></div>
</div></main></div>
<style>.receipt-wrap{width:min(700px,100%);margin:auto}.receipt-page-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.receipt-page-head p{font-size:12px;letter-spacing:.15em;color:#7b8308;margin:0 0 6px}.receipt-page-head h1{margin:0;font-size:26px}.receipt-page-head a,.receipt-actions a{text-decoration:none;color:inherit;display:grid;place-items:center}.receipt-card{background:#fff;border:1px solid #daddd1;border-radius:18px;padding:32px}.receipt-brand{display:flex;align-items:center;gap:14px;padding-bottom:20px;border-bottom:1px dashed #aeb5c2}.receipt-brand img{width:72px;height:72px;border-radius:50%;object-fit:contain;border:1px solid #e2e4dc;padding:5px}.receipt-brand div{display:grid}.receipt-brand strong{letter-spacing:.12em}.receipt-brand span{color:#777b72;margin-top:4px}.receipt-meta{display:grid;grid-template-columns:1fr 1fr;gap:14px;padding:20px 0}.receipt-meta div{display:grid}.receipt-meta span{font-size:12px;color:#777b72}.receipt-meta strong{margin-top:4px}.receipt-items{border-block:1px dashed #aeb5c2;padding:10px 0}.receipt-items>div{display:flex;justify-content:space-between;gap:20px;padding:10px 0}.receipt-items span{display:grid}.receipt-items small{color:#777b72;margin-top:4px}.receipt-total{display:flex;justify-content:space-between;align-items:center;padding-top:22px;font-size:20px}.receipt-total strong{font-size:26px}.receipt-thanks{text-align:center;color:#777b72;margin:28px 0 0}.receipt-actions{display:flex;gap:10px;margin-top:14px}.receipt-actions .button{flex:1}@media(max-width:520px){.receipt-card{padding:20px}.receipt-meta{grid-template-columns:1fr}.receipt-page-head h1{font-size:21px}.receipt-page-head>a{display:none}.receipt-total strong{font-size:22px}}@media print{body{background:#fff}.admin-sidebar,.receipt-page-head,.notice,.receipt-actions{display:none!important}.admin-shell{display:block!important;width:100%!important;height:auto!important;margin:0!important;border:0!important}.admin-workspace{padding:0!important;overflow:visible!important}.receipt-card{border:0;box-shadow:none}}</style>
@endsection
