@extends('layouts.app')
@section('title', 'Customer Information')
@section('content')
<div class="admin-shell">@include('partials.admin-sidebar')<main class="admin-workspace"><div class="dashboard">
    <header class="topbar"><div><h1>Customers</h1><p class="muted">Registered customer accounts and activity</p></div><a class="logout" href="{{ route('dashboard') }}">Dashboard</a></header>
    @if(session('status'))<div class="notice" style="padding:12px;margin-bottom:14px">{{ session('status') }}</div>@endif
    <section class="customer-summary"><div class="welcome"><span>Registered customers</span><h2>{{ $customers->count() }}</h2></div><div class="welcome"><span>Customer orders</span><h2>{{ $customers->sum('orders_count') }}</h2></div><div class="welcome"><span>Customer order value</span><h2>&#8369;{{ number_format($customers->sum('orders_sum_total'),2) }}</h2></div></section>
    <section class="welcome customer-table"><h2>Customer information</h2><table><thead><tr><th>Customer</th><th>Username</th><th>Email</th><th>Phone</th><th>Joined</th><th>Orders</th><th>Reservations</th><th>Total</th><th></th></tr></thead><tbody>@forelse($customers as $customer)<tr><td><div class="customer-name"><span>{{ strtoupper(substr($customer->name,0,1)) }}</span><strong>{{ $customer->name }}</strong></div></td><td>{{ $customer->username ?: 'Not set' }}</td><td>{{ $customer->email }}</td><td>{{ $customer->phone ?: 'Not set' }}</td><td>{{ $customer->created_at->format('M d, Y') }}</td><td>{{ $customer->orders_count }}</td><td>{{ $reservationCounts[$customer->email] ?? 0 }}</td><td>&#8369;{{ number_format($customer->orders_sum_total ?? 0,2) }}</td><td><a href="{{ route('customers.show', $customer) }}">View details</a></td></tr>@empty<tr><td colspan="9" class="empty">No customer accounts yet.</td></tr>@endforelse</tbody></table></section>
</div></main></div>
<style>.topbar h1{font-size:26px}.topbar p{margin:4px 0}.topbar>a{text-decoration:none;color:inherit}.customer-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:20px}.customer-summary .welcome{padding:20px}.customer-summary span{color:#687286}.customer-table{padding:24px;overflow:auto}.customer-table h2{margin-top:0}.customer-table table{width:100%;border-collapse:collapse}.customer-table th{text-align:left;padding:10px}.customer-table td{padding:12px;border-top:1px solid #e7eaf0}.customer-name{display:flex;align-items:center;gap:10px}.customer-name span{width:36px;height:36px;border-radius:50%;background:#e9ecd4;display:grid;place-items:center;color:#747d00;font-weight:800}.customer-table a{white-space:nowrap;color:#596100;font-weight:700}.empty{text-align:center;color:#687286}@media(max-width:700px){.customer-summary{grid-template-columns:1fr}}</style>
@endsection
